spring:
  main:
    banner-mode: OFF
  redis:
    host: localhost
    port: 16379
    password: null
    database: 0
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/example
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 500
server:
  port: 8080
  servlet:
    context-path: /api
